### ISSUE TITLE
Look into hosting the linc-lion webapp via github.io

### ISSUE THREAD

**Issue by leewallen** [linc-lion/linc-webapp#1]
Look into hosting the linc-lion webapp via github.io.  

Github.io provides the ability to:

- [Provide a custom domain name](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages)
- [Enforce the use of https](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https)
- [Easily change visibility to the site](https://docs.github.com/en/pages/getting-started-with-github-pages/changing-the-visibility-of-your-github-pages-site)

Done when:

- [ ] Site is verified to function correctly
- [ ] The site shows the appropriate custom domain
- [ ] Test users have tried out the site to verify that it performs as expected

**Comment by shihgianlee** [comment]
This issue is in the wrong place. We need to explore the possibility of hosting the lionguardians website on github.io, which it doesn't seem to have a repo at the moment. The Webapp needs to stay on heroku.
