### ISSUE TITLE
Document the current web app...

### ISSUE THREAD

**Issue by leewallen** [linc-lion/linc-webapp#2]
Gather information about the current web app:

- How does the web app validate logins?
- How does the web app attempt to pull back info from the database?
- ... from S3?

Done when:

- [x] A document exists that details the services/resources that the web app interfaces with 
- [x] (Optional) - a sequence diagram or state diagram is created that details the interactions between the services/resources

**Comment by shihgianlee** [comment]
Architecture diagram is produced.
